config/routes.rb
Rails.application.routes.draw do

  resources :albums, except: [:new, :index]

  resources :bands do
    resources :albums, only: [:new]
  end

  resource :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: redirect("/bands")
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  band_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  album_type :string           not null
#

class Album < ApplicationRecord
  ALBUM_TYPES = %w(Live Studio)

  validates :title, :band_id, :album_type, presence: true
  validates :album_type, inclusion: {in: ALBUM_TYPES}
  validates :title, uniqueness: { scope: :band_id,
    message: "Single band cannot have two albums of the same name"}

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums, source: :tracks
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  track_type :string           not null
#  title      :string           not null
#  lyrics     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  TRACK_TYPES = %w(Regular Bonus)
  validates :album_id, :track_type, :title, presence: true
  validates :track_type, inclusion: {in: TRACK_TYPES}
  validates :title, uniqueness: { scope: :album_id }

  belongs_to :album
  has_one :band, through: :album, source: :band
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  before_validation :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    session_token = SecureRandom::urlsafe_base64(16)

    while User.where(session_token: session_token).exists?
      session_token = SecureRandom::urlsafe_base64(16)
    end

    session_token
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user.is_password?(password)
    nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @band = Band.find(params[:band_id])
    @album = Album.new
    render :new
  end

  def create
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    return true if current_user
    false
  end



  protected

  def login(user)
    user.reset_session_token!
    user.save
    session[:session_token] = user.session_token
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    Band.find(params[:id]).destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = ["Username and Password don't match"]
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to bands_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<form action="<%= action_url %>" method="post" >
  <% unless method == "post" %>
    <input type="hidden" name="_method" value="<%= method %>">
  <% end %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="title">Enter Album Title</label>
  <br>
  <input id="title" type="text" name="album[title]"
    value="<%= album ? album.title : "" %>">
  <br>
  <br>
  <label for="album_type">Select Album Type</label>
  <br>
  <input id="album_type" type="radio" name="album[album_type]"
    value="Live">Live
  <input id="album_type" type="radio" name="album[album_type]"
    value="Studio">Studio
  <br>
  <br>
  <input type="hidden" name="album[band_id]" value="<%= band_id %>">

  <input type="submit">
</form>

app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

app/views/albums/new.html.erb
<h2>New Album by <%= @band.name %> </h2>

<%= render 'form', album: @album, band_id: @band.id,
  action_url: albums_url, method: 'post' %>

app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

app/views/bands/_form.html.erb
<form action="<%= action_url %>" method="post" >
  <% unless method == "post" %>
    <input type="hidden" name="_method" value="<%= method %>">
  <% end %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="name">Enter Band Name</label>
  <input id="name" type="text" name="band[name]"
    value="<%= band ? band.name : "" %>">
  <br>
  <input type="submit">
</form>

app/views/bands/edit.html.erb
<h1>Edit band</h1>

<%= render 'form', band: @band, action_url: band_url(@band), method: "patch" %>

app/views/bands/index.html.erb
<h2>Bands</h2>

  <br>

  <ul>
    <% @bands.each do |band| %>
      <li><%= link_to "#{band.name}", band_url(band) %></li>
      <!-- Later: replace with link to band's show page -->
    <% end %>
  </ul>

<%= button_to "New Band", new_band_url, method: :get %>

app/views/bands/new.html.erb
<h1>Enter a new band!</h1>

<%= render 'form', action_url: bands_url, method: "post"  %>

app/views/bands/show.html.erb
<h2><%= @band.name %></h2>

  <h4>Albums</h4>

  <br>

  <ul>
    <% @band.albums.each do |album| %>
      <li><%= album.title %></li>
    <% end %>
  </ul>
  <%= button_to "Add new Album", new_band_album_url(@band), method: :get %>
  <%= button_to "Edit this band", edit_band_url(@band), method: :get %>
  <%= button_to "Destroy this band", band_url(@band), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if current_user %>
      <h3>Hello, <%= current_user.email %>!</h3>

      <%= button_to "Logout", sessions_url, method: :delete %>
    <% else %>
      <%= button_to "Login", new_sessions_url, method: :get %>
      <%= button_to "Sign up", new_user_url, method: :get %>
    <% end %>

    <h3> Music App! </h3>

    <%= render "shared/errors" %>

    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% unless flash[:errors].nil? %>
  <p>Errors detected</p>

  <ul>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>

<% end %>

app/views/shared/_user_form.html.erb
<form action="<%= action_url %>" method="post">

  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="email">Email</label>
  <input id="email" type="text" name="user[email]" placeholder="example@example.com">
  <br>
  <label for="password">password</label>
  <input id="password" type="password" name="user[password]" placeholder="password">
  <br>
  <input type="submit">
</form>

app/views/users/new.html.erb
<h2>Sign Up!</h2>

<%= render 'shared/user_form', action_url: users_url %>

app/views/users/show.html.erb
<p>
  sup <%= current_user.email %>
</p>